//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCol
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcDocument_Detail
    {
        public System.Guid Id { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Debtor { get; set; }
        public Nullable<decimal> Creditor { get; set; }
        public System.Guid fk_AcDoc_HeaderId { get; set; }
        public System.Guid fk_PreferentialId { get; set; }
        public System.Guid fk_MoeinId { get; set; }
    
        public virtual AcDocument_Header AcDocument_Header { get; set; }
        public virtual Moein Moein { get; set; }
        public virtual Preferential Preferential { get; set; }
    }
}
