//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCol
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcDocument_Header
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AcDocument_Header()
        {
            this.AcDocument_Detail = new HashSet<AcDocument_Detail>();
            this.CheckPaymentEvents = new HashSet<CheckPaymentEvents>();
            this.CheckRecieveEvents = new HashSet<CheckRecieveEvents>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime Date { get; set; }
        public long Serial { get; set; }
        public long NoDoument { get; set; }
        public System.Guid fk_DocumentTypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcDocument_Detail> AcDocument_Detail { get; set; }
        public virtual DocumentType DocumentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckPaymentEvents> CheckPaymentEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckRecieveEvents> CheckRecieveEvents { get; set; }
    }
}
