//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCol
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckPaymentEvent
    {
        public System.Guid Id { get; set; }
        public System.Guid fk_DetaiId { get; set; }
        public Nullable<System.Guid> fk_AcId { get; set; }
        public System.Guid fk_ChEventId { get; set; }
        public System.DateTime EventDate { get; set; }
        public System.Guid fk_PreferentialId { get; set; }
        public System.Guid fk_MoeinId { get; set; }
        public string Description { get; set; }
        public int Indexer { get; set; }
    
        public virtual AcDocument_Header AcDocument_Header { get; set; }
        public virtual ChEvent ChEvent { get; set; }
        public virtual Moein Moein { get; set; }
        public virtual PaymentMoney_Detail PaymentMoney_Detail { get; set; }
        public virtual Preferential Preferential { get; set; }
    }
}
