//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCol
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChEvent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChEvent()
        {
            this.CheckPaymentEvent = new HashSet<CheckPaymentEvent>();
            this.CheckRecieveEvent = new HashSet<CheckRecieveEvent>();
        }
    
        public System.Guid Id { get; set; }
        public byte ChEventCode { get; set; }
        public string Name { get; set; }
        public bool ForMoney { get; set; }
        public bool ForPayment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckPaymentEvent> CheckPaymentEvent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckRecieveEvent> CheckRecieveEvent { get; set; }
    }
}
