//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCol
{
    using System;
    using System.Collections.Generic;
    
    public partial class Col
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Col()
        {
            this.Moein = new HashSet<Moein>();
        }
    
        public System.Guid Id { get; set; }
        public int ColCode { get; set; }
        public string ColName { get; set; }
        public Nullable<byte> Type { get; set; }
        public Nullable<byte> Action { get; set; }
        public System.Guid fk_GroupId { get; set; }
        public Nullable<bool> PermissionView { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Moein> Moein { get; set; }
        public virtual AGroup AGroup { get; set; }
    }
}
