//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCol
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommodityPricingPanel
    {
        public System.Guid Id { get; set; }
        public System.Guid fk_PriceGroupId { get; set; }
        public System.Guid fk_CommodityId { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Commodity Commodity { get; set; }
        public virtual PriceGroup PriceGroup { get; set; }
    }
}
