//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCol
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ColDbEntities1 : DbContext
    {
        public ColDbEntities1()
            : base("name=ColDbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AcDocument_Detail> AcDocument_Detail { get; set; }
        public virtual DbSet<AcDocument_Header> AcDocument_Header { get; set; }
        public virtual DbSet<AGroup> AGroup { get; set; }
        public virtual DbSet<Bank> Bank { get; set; }
        public virtual DbSet<ChEvent> ChEvent { get; set; }
        public virtual DbSet<Col> Col { get; set; }
        public virtual DbSet<DocumentType> DocumentType { get; set; }
        public virtual DbSet<Moein> Moein { get; set; }
        public virtual DbSet<PaymentMoney_Detail> PaymentMoney_Detail { get; set; }
        public virtual DbSet<PaymentMoneyHeader> PaymentMoneyHeader { get; set; }
        public virtual DbSet<Preferential> Preferential { get; set; }
        public virtual DbSet<RecieveMoney_Detail> RecieveMoney_Detail { get; set; }
        public virtual DbSet<RecieveMoneyHeader> RecieveMoneyHeader { get; set; }
        public virtual DbSet<tGroup> tGroup { get; set; }
        public virtual DbSet<CodeSetting> CodeSetting { get; set; }
        public virtual DbSet<CheckPaymentEvent> CheckPaymentEvent { get; set; }
        public virtual DbSet<CheckRecieveEvent> CheckRecieveEvent { get; set; }
    }
}
