//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCol
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentMoneyHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentMoneyHeader()
        {
            this.PaymentMoney_Detail = new HashSet<PaymentMoney_Detail>();
        }
    
        public System.Guid Id { get; set; }
        public int ReceiptNumber { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.Guid> fk_PreferentialId { get; set; }
        public Nullable<System.Guid> fk_MoeinId { get; set; }
        public string Description { get; set; }
    
        public virtual Moein Moein { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentMoney_Detail> PaymentMoney_Detail { get; set; }
        public virtual Preferential Preferential { get; set; }
    }
}
