//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCol
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preferential
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Preferential()
        {
            this.AcDocument_Detail = new HashSet<AcDocument_Detail>();
        }
    
        public System.Guid Id { get; set; }
        public int PreferentialCode { get; set; }
        public System.Guid fk_GroupId { get; set; }
        public string PreferentialName { get; set; }
        public string Mobile { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Phone3 { get; set; }
        public string WebSite { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcDocument_Detail> AcDocument_Detail { get; set; }
        public virtual tGroup tGroup { get; set; }
    }
}
