//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCol
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preferential
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Preferential()
        {
            this.PaymentMoneyHeader = new HashSet<PaymentMoneyHeader>();
            this.RecieveMoneyHeader = new HashSet<RecieveMoneyHeader>();
            this.AcDocument_Detail = new HashSet<AcDocument_Detail>();
            this.CheckPaymentEvent = new HashSet<CheckPaymentEvent>();
            this.CheckRecieveEvent = new HashSet<CheckRecieveEvent>();
            this.PaymentMoney_Detail = new HashSet<PaymentMoney_Detail>();
            this.RecieveMoney_Detail = new HashSet<RecieveMoney_Detail>();
            this.OrderHeader = new HashSet<OrderHeader>();
            this.ProductBuyHeader = new HashSet<ProductBuyHeader>();
            this.ProductSellHeader = new HashSet<ProductSellHeader>();
            this.ProductSellHeader1 = new HashSet<ProductSellHeader>();
            this.ProductSellHeader2 = new HashSet<ProductSellHeader>();
            this.ProductSellHeader3 = new HashSet<ProductSellHeader>();
            this.ProductSellHeader4 = new HashSet<ProductSellHeader>();
            this.PreInvoiceHeader = new HashSet<PreInvoiceHeader>();
        }
    
        public System.Guid Id { get; set; }
        public int PreferentialCode { get; set; }
        public System.Guid fk_GroupId { get; set; }
        public string PreferentialName { get; set; }
        public string Mobile { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Phone3 { get; set; }
        public string WebSite { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> fk_CityId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentMoneyHeader> PaymentMoneyHeader { get; set; }
        public virtual tGroup tGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecieveMoneyHeader> RecieveMoneyHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcDocument_Detail> AcDocument_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckPaymentEvent> CheckPaymentEvent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckRecieveEvent> CheckRecieveEvent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentMoney_Detail> PaymentMoney_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecieveMoney_Detail> RecieveMoney_Detail { get; set; }
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderHeader> OrderHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductBuyHeader> ProductBuyHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSellHeader> ProductSellHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSellHeader> ProductSellHeader1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSellHeader> ProductSellHeader2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSellHeader> ProductSellHeader3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSellHeader> ProductSellHeader4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreInvoiceHeader> PreInvoiceHeader { get; set; }
    }
}
