//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCol
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreInvoiceHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PreInvoiceHeader()
        {
            this.PreInvoice_Detail = new HashSet<PreInvoice_Detail>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime Date { get; set; }
        public long Serial { get; set; }
        public System.Guid fk_PreferentialId { get; set; }
        public Nullable<decimal> InvoiceDiscount { get; set; }
        public string Description { get; set; }
        public decimal SumDiscount { get; set; }
    
        public virtual Preferential Preferential { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreInvoice_Detail> PreInvoice_Detail { get; set; }
    }
}
