//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCol
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSellHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductSellHeader()
        {
            this.ProductSell_Detail = new HashSet<ProductSell_Detail>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime Date { get; set; }
        public long Serial { get; set; }
        public Nullable<long> OrderNumber { get; set; }
        public long InvoiceNumber { get; set; }
        public string WayBillNumber { get; set; }
        public string CarPlate { get; set; }
        public string CarType { get; set; }
        public System.Guid fk_PreferentialId { get; set; }
        public Nullable<decimal> InvoiceDiscount { get; set; }
        public Nullable<decimal> ShippingCost { get; set; }
        public string Description { get; set; }
        public decimal SumDiscount { get; set; }
        public Nullable<System.Guid> fk_PreferentialId_receiver { get; set; }
        public Nullable<System.Guid> fk_PreferentialId_freight { get; set; }
        public Nullable<System.Guid> fk_PreferentialId_driver { get; set; }
        public Nullable<System.Guid> fk_PreferentialId_personnel { get; set; }
    
        public virtual Preferential Preferential { get; set; }
        public virtual Preferential Preferential1 { get; set; }
        public virtual Preferential Preferential2 { get; set; }
        public virtual Preferential Preferential3 { get; set; }
        public virtual Preferential Preferential4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSell_Detail> ProductSell_Detail { get; set; }
    }
}
