//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCol
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductBuyHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductBuyHeader()
        {
            this.ProductBuy_Detail = new HashSet<ProductBuy_Detail>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime Date { get; set; }
        public long Serial { get; set; }
        public Nullable<long> OrderNumber { get; set; }
        public long InvoiceNumber { get; set; }
        public string WayBillNumber { get; set; }
        public string CarPlate { get; set; }
        public string CarType { get; set; }
        public System.Guid fk_PreferentialId { get; set; }
        public Nullable<decimal> InvoiceDiscount { get; set; }
        public Nullable<decimal> ShippingCost { get; set; }
        public string Description { get; set; }
        public decimal SumDiscount { get; set; }
    
        public virtual Preferential Preferential { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductBuy_Detail> ProductBuy_Detail { get; set; }
    }
}
