//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCol
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageReceiptHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StorageReceiptHeader()
        {
            this.StorageReceipt_Detail = new HashSet<StorageReceipt_Detail>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime Date { get; set; }
        public long Serial { get; set; }
        public long NoDoument { get; set; }
        public System.Guid fk_StorageId { get; set; }
        public System.Guid fk_CodingReceiptTypesId { get; set; }
        public string Description { get; set; }
    
        public virtual CodingReceiptTypes CodingReceiptTypes { get; set; }
        public virtual Storage Storage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StorageReceipt_Detail> StorageReceipt_Detail { get; set; }
    }
}
