//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCol
{
    using System;
    using System.Collections.Generic;
    
    public partial class Storage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Storage()
        {
            this.StorageReceiptHeader = new HashSet<StorageReceiptHeader>();
            this.StorageTransferHeader = new HashSet<StorageTransferHeader>();
        }
    
        public System.Guid Id { get; set; }
        public int StorageCode { get; set; }
        public System.Guid fk_GroupId { get; set; }
        public string StorageName { get; set; }
    
        public virtual GroupStorage GroupStorage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StorageReceiptHeader> StorageReceiptHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StorageTransferHeader> StorageTransferHeader { get; set; }
    }
}
